image: golang:1.11

variables:
  REPO_NAME: gitlab.liu.se/danhe178/tdde06-lab3

before_script:
  - go get -d -v ./...
  - apt-get -qq update
  - apt-get install -y sqlite3-doc

stages:
    - build
    - test
    
build:
    stage: build
    script:
        - echo "Building"
        - sqlite3 foo.db < schema.sql
        - go build -x todo.go
    artifacts:
        paths:
            - todo
            - foo.db

test:
    stage: test
    script:
        - echo "Testing"
        - ls
        - go test -x