image: golang:1.11

variables:
  REPO_NAME: gitlab.liu.se/danhe178/tdde06-lab3

before_script:
  - go version
  - go get -d -v ./...
  - apt-get -qq update
  - apt-get install -y postgresql

stages:
    - build
    - test
    
build:
    stage: build
    script:
        - echo "Building again"
        - psql -f schema.sql db_name
        - go build todo.go
    artifacts:
        paths:
            - todo
            - db_name

test:
    stage: test
    script:
        - echo "Testing"
        - ls
        - go test