image: golang:1.11

before_script:
  - go get -d -v ./...
  - apt-get -qq update
  - apt-get install -y sqlite3-doc

stages:
    - build
    - test
    - run
    
build:
    stage: build
    script:
        - echo "Building"
        - sqlite3 foo.db < schema.sql
        - go build todo.go
    artifacts:
        paths:
            - todo
            - foo.db

test:
    stage: test
    script:
        - echo "Testing"
        - ls
        - go test
        
run:
    stage: run
    script:
        - echo "Running"
        - ls
        - ./todo &
        - pkill todo
        